Repository hlxsites/mammotome, pull requests merged in 2023-07, with the labels that each got.

#387 Accessibility fixes
  blocks/carousel/carousel.js
  blocks/product-reference/product-reference.js
Labels: bug, accessibility

#390 Add support for videos in product support
  blocks/product-support/product-support.css
  blocks/product-support/product-support.js
  blocks/video/video.js
Labels: enhancement

#394 improve carousel for smaller images
  blocks/carousel/carousel.css
  blocks/carousel/carousel.js
Labels: enhancement

#407 fix: also support parameters in form link
  blocks/form/form.js
Labels: bug

#408 fix: translate keys correctly
  blocks/ifus/ifus.js
  blocks/product-reference/product-reference.js
Labels: bug

#399 feat(form): wizard implementation
  blocks/form/form.css
  blocks/form/form.js
  blocks/form/wizard.js
Labels: enhancement

#393 fix: checkbox with same name not working correctly when required
  blocks/form/checkbox.js
  blocks/form/form.css
  blocks/form/form.js
Labels: bug

#420 fix: re-add language support (overwritten by other p)
  blocks/form/form.js
Labels: bug

#409 feat: background-image optimization
  scripts/scripts.js
Labels: enhancement

#429 fix: product support reference url
  blocks/product-list/product-list.js
  blocks/product-reference/product-reference.js
Labels: bug

#431 Remove bottom video padding
  blocks/video/video.css
Labels: bug

#432 Our History: Calendar Icon fix
  styles/styles.css
Labels: bug

#467 fix: video container top/bottom spacing
  blocks/video/video.css
Labels: bug

#494 feat: introduce templating mechanism
  scripts/scripts.js
  templates/legacy/script.js
  templates/legacy/styles.css
  templates/refresh/script.js
  templates/refresh/styles.css
Labels: enhancement, refresh-design

#502 fix: replace :has selector
  blocks/columns/columns.js
  blocks/header/header.css
  blocks/header/header.js
  blocks/video/video.css
  styles/styles.css
Labels: bug

#505 chore: remove all arcs
  blocks/cards/cards.css
  blocks/collapsible/collapsible.css
  blocks/columns/columns.css
  blocks/hero/hero.css
  docs/section-metadata.md
  scripts/scripts.js
  styles/styles.css
Labels: enhancement

#500 feat: refresh style footer
  blocks/footer/footer.css
  blocks/header/header.css
  blocks/header/header.js
  scripts/lib-franklin.js
  scripts/scripts.js
  styles/styles.css
  templates/legacy/script.js
  templates/legacy/styles.css
  templates/refresh/script.js
  templates/refresh/styles.css
Labels: enhancement

#506 fix: text align footer heading
  blocks/footer/footer.css
Labels: bug

#508 feat: header style update
  blocks/cards/cards.css
  blocks/form/form.css
  blocks/form/form.js
  blocks/header/header.css
  blocks/header/header.js
  scripts/lib-franklin.js
  styles/styles.css
Labels: enhancement, refresh-design

#514 fix: optimize nav search icon placement
  blocks/header/header.css
  blocks/header/header.js
Labels: bug

#503 feat: hero carousel
  blocks/carousel/carousel.css
  blocks/carousel/carousel.js
  blocks/hero-carousel/hero-carousel.css
  blocks/hero-carousel/hero-carousel.js
  docs/assets/hero-carousel-1-example.png
  docs/assets/hero-carousel-2-example.png
  docs/assets/hero-carousel-table-example.png
  docs/block-collection.md
  docs/blocks/hero-carousel.md
  scripts/lib-carousel.js
Labels: enhancement, refresh-design

#517 add refresh-design divider secondary option
  docs/assets/divider-blue-example.png
  docs/section-metadata.md
  scripts/lib-franklin.js
  styles/styles.css
Labels: enhancement, refresh-design

#520 feat: subnavigation and metrics styles
  blocks/columns/columns.css
  blocks/columns/columns.js
  docs/assets/columns-metrics.png
  docs/assets/columns-subnavigation.png
  docs/blocks/columns.md
  docs/section-metadata.md
  scripts/lib-franklin.js
  styles/styles.css
Labels: enhancement, refresh-design

#522 feat: general styles (WIP)
  blocks/columns/columns.css
  blocks/footer/footer.css
  blocks/header/header.css
  styles/styles.css
Labels: enhancement, refresh-design

#512 feat: introduce anchor links on for specified products
  blocks/form/form.css
  blocks/product-reference/product-reference.css
  blocks/product-reference/product-reference.js
Labels: enhancement
