Repository hlxsites/mammotome, pull requests merged in 2023-08, with the labels that each got.

#525 fix: reduce GTM loading time
  scripts/delayed.js
  scripts/scripts.js
Labels: enhancement

#526 fix header image cut off
  blocks/hero-carousel/hero-carousel.css
Labels: bug

#528 fix: optimize background image for breakpoints
  scripts/scripts.js
Labels: bug

#531 Revert "fix header image cut off (#526)"
  blocks/hero-carousel/hero-carousel.css
Labels: bug

#538 Product carousel
  blocks/hero-carousel/hero-carousel.js
  blocks/product-carousel/product-carousel.css
  blocks/product-carousel/product-carousel.js
  docs/assets/product-carousel-example.png
  docs/assets/product-carousel-table-example.png
  docs/block-collection.md
  docs/blocks/hero-carousel.md
  docs/blocks/product-carousel.md
  scripts/lib-carousel.js
Labels: refresh-design
