Repository hlxsites/mammotome, pull requests merged in 2023-04, with the labels that each got.

#47 feat: Site Search
  blocks/header/header.css
  blocks/header/header.js
Labels: enhancement

#53 feat: i18n placeholders
  blocks/header/header.css
  blocks/header/header.js
  scripts/delayed.js
  scripts/lib-franklin.js
Labels: enhancement

#54 feat: Cookie Consent
  scripts/delayed.js
Labels: enhancement

#30 feat: top navigation
  blocks/header/header.css
  blocks/header/header.js
  icons/logo-round.webp
  styles/styles.css
  test/blocks/header/header.test.js
Labels: enhancement

#60 feat: Global i18n and config
  blocks/header/header.js
  scripts/delayed.js
  scripts/lib-franklin.js
Labels: enhancement

#58 feat: pdf viewer
  blocks/pdf-viewer/pdf-viewer.css
  blocks/pdf-viewer/pdf-viewer.js
  scripts/delayed.js
  scripts/lib-franklin.js
  scripts/scripts.js
Labels: enhancement

#62 fix: carousel vertical alignment
  blocks/carousel/carousel.css
Labels: bug

#56 feat: Top Navigation - follow up
  blocks/header/header.css
  blocks/header/header.js
  styles/styles.css
Labels: enhancement

#50 feat: section styles
  scripts/scripts.js
  styles/icons/Mammotome-BG_Pattern-1.svg
  styles/icons/Mammotome-BG_Pattern-2.svg
  styles/styles.css
Labels: enhancement

#75 fix: exclude nav, footer and experiments from index
  helix-query.yaml
Labels: configuration
