Repository hlxsites/mammotome, pull requests merged in 2023-06, with the labels that each got.

#202 feat: update mountpoint to new location
  fstab.yaml
Labels: configuration

#203 Adjust nav and footer lookup to country and language structure.
  .github/pull_request_template.md
  fstab.yaml
  scripts/lib-franklin.js
Labels: enhancement

#204 Rename product db
  scripts/lib-franklin.js
Labels: enhancement

#210 feat: add revisions to the eIFUs
  blocks/ifus/ifus.js
Labels: enhancement

#211 Adjust the search to the new country/language layout
  blocks/header/header.js
  blocks/ifus/ifus.js
  scripts/lib-franklin.js
Labels: bug

#215 Cleanup productdb info lookup
  blocks/header/header.js
  blocks/ifus/ifus.js
  blocks/product-list/product-list.js
  blocks/product-reference/product-reference.js
  blocks/product-support/product-support.js
  scripts/lib-franklin.js
Labels: enhancement

#228 fix: adjust to new country/language structure
  helix-query.yaml
  helix-sitemap.yaml
  robots.txt
Labels: configuration

#157 feat: move icons into sharepoint
  blocks/header/header.js
  icons/logo-round.webp
Labels: enhancement

#303 Add product support folders for all languages
  fstab.yaml
Labels: enhancement

#162 feat: style mammotome forms
  blocks/form/file.js
  blocks/form/form.css
  blocks/form/form.js
  blocks/hero/hero.css
  styles/icons/circle.svg
  styles/styles.css
Labels: enhancement

#341 fix: ifus align should only target headers below ifus block
  blocks/ifus/ifus.css
Labels: bug

#343 fix: hide pdf link
  blocks/pdf-viewer/pdf-viewer.css
Labels: bug

#344 fix: decorateButtons tries to detect pdfs before it adds button container
  scripts/lib-franklin.js
Labels: bug

#359 fix: IFU result buttons text uppercase
  blocks/ifus/ifus.css
Labels: bug

#381 fix: nav-overflow button SEO
  blocks/header/header.js
Labels: bug, seo

#383 fix: add aria-label / title for linked svg
  blocks/footer/footer.css
  blocks/header/header.js
  scripts/lib-franklin.js
Labels: bug, accessibility
